services:
  web:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/wids/data-agent:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - POSTGRES_URL=postgresql://postgres:supersecretpassword@web-db:5432/web_dev
      - POSTGRES_TEST_URL=postgresql://postgres:supersecretpassword@web-db:5432/web_test
    depends_on:
      - web-db
  
  web-db:
    build:
      context: ./api/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
